apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment   # MUST match Jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend        # MUST match Jenkins
        image: daneshkabade45/frontend:latest
        ports:
        - containerPort: 80
